yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorPage.as_view(), name='author'),
    path('tech/', views.AboutTechPage.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts_detail'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/', views.group_posts, name='posts_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/delete/', views.post_delete, name='post_delete'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path(
        'posts/comments/<int:comment_id>/delete/',
        views.comment_delete, name='delete_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),
] 

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
import posts.urls

app_name = 'posts'

urlpatterns = [
    path('', include(posts.urls, namespace='posts')),
    path('admin/', admin.site.urls),   
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')), 
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()
    def __str__(self):
        return f"{self.title}"
    

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='group'
    )

    def __str__(self):
        return str(self.id)

class Comment(CreatedModel):
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Текст вашего комментария'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    def __str__(self):
        return self.text[:15]


class Follow(CreatedModel):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group',)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow, Comment
from . forms import PostForm, CommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

def index(request):
    title = 'Последние обновления на сайте'
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10) 
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context) 

def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    post_list = group.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context) 

def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = False
    if request.user.is_authenticated:
        following = request.user.follower.filter(author=author).exists()
    post_list = author.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)

@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        temp_form = form.save(commit=False)
        temp_form.author = request.user
        temp_form.save()
        return redirect(
            'posts:profile', temp_form.author
        )
    return render(request, template, {'form': form})


def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect(
            'posts:post_detail', post_id
        )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail', post_id
        )
    return render(request, template, {
        'form': form, 'is_edit': True, 'post': post
    })


@login_required
def add_comment(request, post_id):
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = get_object_or_404(Post, pk=post_id)
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    title = 'Публикации избранных авторов'
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': title,
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    follow_author = get_object_or_404(User, username=username)
    if follow_author != request.user and (
        not request.user.follower.filter(author=follow_author).exists()
    ):
        Follow.objects.create(
            user=request.user,
            author=follow_author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    follow_author = get_object_or_404(User, username=username)
    data_follow = request.user.follower.filter(author=follow_author)
    if data_follow.exists():
        data_follow.delete()
    return redirect('posts:profile', username)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
    return redirect('posts:profile', post.author.username)


@login_required
def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment.author == request.user:
        comment.delete()
    return redirect('posts:post_detail', post_id=comment.post.pk)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load user_filters %}
{% block content %} 
<style>
  textarea {
  width: 100%; /* Ширина поля в процентах */
  height: 175px; /* Высота поля в пикселах */
  }
</style>
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if is_edit %}
            Сохранить запись
          {% else %}
            Добавить запись
          {% endif %}             
        </div>
        <div class="card-body">
        
        {% if is_edit %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' post.pk %}">
        {% else %}
          <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
        {% endif %}  
          {% csrf_token %}
           
            {% for field in form %}
            <div class="form-group row my-3 p-3 textarea">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>    
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                  {{ field.help_text|safe }}
                </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
  <div class="container col-lg-9 col-sm-12">
    <ul>
    <li>
      <b>Автор:</b>
      <a href="{% url 'posts:profile' post.author %}">{{ post.author.get_full_name }}</a>
    </li>
    <li>
      <b>Дата публикации:</b> {{ post.pub_date|date:"d E Y" }}
    </li>
    {% if post.group %}
    <li>
      <p><b>Группа:</b> 
      <a href="{% url 'posts:group_list' post.group.slug %}">{{ post.group.title }}</a></p>
    </li>
    {% endif %}
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaks }}</p>
    <a href="{% url 'posts:post_detail' post.pk %}">(подробная информация)</a>    
    {% if not forloop.last %}<hr>{% endif %}
  </div>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 
    

yatube/templates/posts/group_list.html
<!DOCTYPE html>
{% extends 'base.html' %}   
{% block title %}
    <title>{{group.title}}</title>
{% endblock %}  
{% block content %}
{{ text }}    
{% endblock %}

yatube/templates/posts/index.html
<!DOCTYPE html> <!-- Используется html 5 версии -->
{% extends 'base.html' %}
{% block h1 %} 
<div class="container">
<h1>Последние обновления на сайте</h1>
</div>
{% endblock %}
{% block content %}
{% for post in page_obj %}
<div class="container">
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>    
</div>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
<div class="container">
{% include 'posts/includes/paginator.html' %}
</div>
{{ text }}
<div class="container">
   <h1>Поиск по записям</h1>

   <div class="card">
     <div class="card-body">

       <form class="form-inline" action="/">
         <div class="form-row">
         <input name="q" class="form-control form-control-lg" type="search" 
           placeholder="Поиск" {% if keyword %}value="{{ keyword }}"{% endif %}>
         <button class="btn" type="submit">Найти</button>
         </div>
       </form>
       </div>
     </div>
   </div>
</div>
{% endblock %}  
{% block groups %}
{% if post.group %}    
   <a href="{% url 'posts:posts_detail' post.group.slug %}">все записи группы</a>
{% endif %} 
{%endblock%}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
{% load user_filters %}
<style>
  textarea {
  width: 100%; /* Ширина поля в процентах */
  height: 70px; /* Высота поля в пикселах */
  }
</style>
<div class="container col-lg-9 col-sm-12">
  <div class="row">
    <aside class="col-12 col-md-4">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <b>Дата публикации:</b><br> {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            <b>Группа:</b>
            <a href="{% url 'posts:posts_detail' post.group.slug %}">{{ post.group.title }}</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          <b>Автор:</b>
        </li>
        <li class="list-group-item">
          <b>Всего постов автора:</b> {{ post.author.posts.count }}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-8">

      <p>
        {{ post.text|linebreaks }}
      </p>
      {% if post.author == user %}
      <a href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>&nbsp;&nbsp;&nbsp;
      <a href="{% url 'posts:post_delete' post.pk %}">удалить запись</a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h6 class="card-header">Добавить комментарий:</h6>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}
              <div class="form-group mb-4 textarea">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.get_full_name }}
              </a>
            </h5>
              <p>
              {{ comment.text }}
              {% if post.author == user %}
              <br>
              <a href="{% url 'posts:delete_comment' comment.pk %}">удалить запись</a>
              {% endif %}
              {% if not forloop.last %}<hr>{% endif %}
              </p>
          </div>
        </div>
      {% endfor %}
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container col-lg-9 col-sm-12">
  <h2>Все посты пользователя {{ author.get_full_name }} </h2>
  <h3>Всего постов: {{ author.posts.count }}</h3>
    {% if user != author %}
      {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
      {% else %}
            Подписаться
          </a>
      {% endif %}
    {% endif %}
   <br><br>
  {% for post in page_obj %}
    <article>
    <ul>
      <li>
        Автор: {{ author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
        {% if post.group %}
        <li>
            <p>Группа:
            <a href="{% url 'posts:posts_detail' post.group.slug %}">{{ post.group.title }}</a></p>
        </li>
        {% endif %}
    </ul>
      <img class="card-img my-2" src="{{ im.url }}">
    <p>
    {{ post.text|linebreaks }}
    <a href="{% url 'posts:post_detail' post.pk %}">(подробная инфомация)</a>
    </p>
    </article>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}